name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Running spell check with vale
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: docs
          fail_on_error: true

      - name: Lint md files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: '.markdownlint.json'
          globs: './docs/**/*.md'

      - name: Lint mdx files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: '.markdownxlint.json'
          globs: './docs/**/*.mdx'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
